### ISSUE TITLE
b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#136]
**Description:**
New coupled simulation including
- corrected sandbox for cam (revice bugfix) 
- new topo file: 
```
/glade/p/cgd/amp/juliob/bndtopo/latest/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_20220622.nc
```
- bugfix for salinity conservation issue and 
```
saltflux_option = 'prognostic'
```

**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009

On github:
https://github.com/NCAR/amwg_dev/tree/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009

**Sandbox:**
Locally (if still available):
/glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_c

On github:
https://github.com/NCAR/amwg_dev/tree/cesm3_cam6_3_058_MOM
hash: [b655f7d](https://github.com/ESCOMP/CESM/commit/b655f7d08fc4bb7c4a48589e3fcf56f16b05db5c)

**Diagnostics:**
AMWG diags (if available)
[https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009//atm/)

**Contacts:**
@cecilehannay and @gustavo-marques

**Comment by cecilehannay** [comment]
@gustavo-marques: I am getting an error with the ``saltflux_option``

```
/glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_c/components/cice/src/cicecore/cicedynB/analysis/ice_diagnostics.F90(224): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [SALTFLUX_OPTION_OUT]
           snwgrain_out=snwgrain, saltflux_option_out=saltflux_option)
----------------------------------^
compilation aborted for /glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_c/components/cice/src/cicecore/cicedynB/analysis/ice_diagnostics.F90 (code 1)
gmake: *** [ice_diagnostics.o] Error 1
```

**Comment by jedwards4b** [comment]
I don't see the saltflux_option in icepack_parameters.F90

**Comment by cecilehannay** [comment]
[dabail10](https://github.com/dabail10)updated the cice externals and it solved the issue. 
This run uses the hash: [228563a](https://github.com/ESCOMP/CESM/commit/228563afb0ed64101681f5170474b743fa683e1d)

The run is now 9 years.

**Comment by gustavo-marques** [comment]
So far (year 10) the ocean state looks reasonable. Deep convection is still occurring in the Labrador Sea. The plot below shows the mixed layer depth (MLD) for February of year 9, with the inset showing the MLD time series taken from a point near the southern tip of Greenland. 
 
![image](https://user-images.githubusercontent.com/11339137/176303672-659e52b5-77a5-4409-a5a9-c751c2c099fb.png)

**Comment by gustavo-marques** [comment]
The simulation has completed 12 years and it looks like convection in the Labrador Sea is getting weaker :worried:

**Comment by JulioTBacmeister** [comment]
OK.  I still say let's let it go another 8 years.

**Comment by justin-richling** [comment]
The ADF diags for the CMIP6 case are [here](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_1_10_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_1_10/).

There are issues with the Taylor Diagram at the moment, so those and AMWG tables are missing. I am working on getting those fixed and will update soon, but the rest should be good.

The comparison with Obs is currently running and I will update when those are finished

**Comment by justin-richling** [comment]
ADF diags for comparison vs Obs are [here](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_1_10_vs_obs/)

**Comment by cecilehannay** [comment]
It looks there is a problem with the SSTs value on the [table](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_1_10_vs_obs/html_table/amwg_table_b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009.html):  
Please ignore the SST value on that table. We will look into that.

**Comment by JulioTBacmeister** [comment]
Also looks like the SSTs in the latlon plots may also be "weird"

**Comment by justin-richling** [comment]
[Taylor diagrams](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_1_10_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_1_10/html_img/mean_diag_TaylorDiag.html) are now fixed for the CMIP6 case

**Comment by cecilehannay** [comment]
The run is now 20 years. We are aware that the convection in the Labrador Sea is getting weaker. But @JulioTBacmeister and the cam folks would be VERY interested in letting it go another 20 years.  There are clearly some big shocks in the first decade and we need more years to assess this clearly.

@gustavo-marques: what do you think?

**Comment by gustavo-marques** [comment]
Yes, let's run it for another 20 years. Convection is still happening in the Irminger and Nordic Seas. The Lab Sea is entirely covered by sea ice in the winter, but the ice melts during summer.

**Comment by JulioTBacmeister** [comment]
Great!  Maybe Lab Sea ice cover in winter will begin to decrease ...

**Comment by cecilehannay** [comment]
We have 55 years now. It would be good to run the diags in the morning.

**Comment by JulioTBacmeister** [comment]
Quick and dirty IDL diagnostics (below): global TS keeps falling despite global RESTOM averaging around 0.20 to 0.3 Wm-2

![image](https://user-images.githubusercontent.com/9221710/177240258-aba4af85-a193-426f-b7e7-b4a48d5efdcb.png)


![image](https://user-images.githubusercontent.com/9221710/177240328-6cbf6131-d2ee-407c-b4d9-1383e4e2a794.png)

Appears to high-latitude cooling that is driving the global mean.  A map of mean TS from years 45-54 compared to years 30-45:
![image](https://user-images.githubusercontent.com/9221710/177240525-79401fc1-2802-4c5f-876b-8039449708fa.png)

**Comment by cecilehannay** [comment]
This is quite a drop in global TS.  Do you know whether it is happening over ocean (or also land)? 
I wonder if we have a redistribution of the heat in the ocean. It would be nice if @gustavo-marques could look of contours of temperature with time/depth.

**Comment by cecilehannay** [comment]
Indeed your second plot answers to my question about the location of the TS cooling. (sorry I missed the second plot in my email).  
This is the high latitude TS.

**Comment by swrneale** [comment]
@JulioTBacmeister could you tighten your contour interval on your plots as I suspect the ocean could also be cooling at 0-0.5K most places?

**Comment by adamrher** [comment]
this is a minor point I think, but we would ideally be running with the exchange grid, as we are currently computing fluxes on the MOM grid. In ```nuopc.runconfig```

```
     aoflux_grid = ogrid
```

**Comment by justin-richling** [comment]
The ADF diags for the years 40-59 vs CMIP6 case are [here](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_40_59_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_40_59/index.html), comparison vs Obs will be up soon

**Comment by JulioTBacmeister** [comment]
@swrneale Contours tightened. Now comparing Yrs 45-57 with 30-45.  Clearly cooling isn't restricted to high latitudes but is more intense there.  Will have a look at regional timeseries.

**Comment by cecilehannay** [comment]
From looking at ICEFRAC, the lab sea might be still ok. (?)
https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_40_59_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_40_59/html_img/plot_page_ICEFRAC_ANN_NHPolar.html

**Comment by gustavo-marques** [comment]
Here are global depth versus time temperature biases (model - world ocean atlas). Surface ocean is cooling. Mid-depth ocean is warming a little.
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_Global_temp_diff](https://user-images.githubusercontent.com/11339137/177370886-1936ee4f-33c7-4020-bc16-a6c0edb75c7c.png)

Below is the coupler heat budget (all time up to year 58). It's shown that the ocean is cooling, which is consistent with the plot above. Fluxes are into the atmosphere from all components. Land and ice fluxes to the ATM are both larger than the ocean. 
![image](https://user-images.githubusercontent.com/11339137/177375802-62f78d05-8443-487c-91da-4ddc7a65904b.png)

**Comment by JulioTBacmeister** [comment]
Time series in different ocean basins. Definitions are fairly standard.  Main point is that tropical oceans (30S-30S) are not cooling, may even be warming after Year 31.

![image](https://user-images.githubusercontent.com/9221710/177376422-13eb003a-c974-49fe-ae82-00acf9875606.png)

**Comment by justin-richling** [comment]
ADF diags for years 40-59 vs Obs are [here](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_40_59_vs_obs/)

Misisng AMWG table for b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009 are now added to the CMPI6 case as well, see [here](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_40_59_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_40_59/html_table/amwg_table_b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009.html)

**Comment by JulioTBacmeister** [comment]
Apologies inadvertently closed comment/issue. Not sure which. Anyway looks like like I need to reattach time series of TS in different ocean basins. Note TS in Year 1 is subtracted.  @gustavo-marques it would be interesting to see you temperature curtain plots in different basins as well. Is that possible?
  
![image](https://user-images.githubusercontent.com/9221710/177379224-97cc5c9d-c991-4870-ba64-c0fd10feb0e4.png)

**Comment by gustavo-marques** [comment]
@JulioTBacmeister: yes, here are plots for a few basins.

### Lab Sea
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_LabSea_temp_diff](https://user-images.githubusercontent.com/11339137/177380316-6425b8f7-81f3-4fd6-8c7a-88c1f39dc3be.png)

### Southern Ocean
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_SouthernOcean_temp_rms](https://user-images.githubusercontent.com/11339137/177380457-aac9c56c-cd39-4c2d-a7d6-d3d8cdbdc2a9.png)

### Indian Ocean
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_IndianOcean_temp_diff](https://user-images.githubusercontent.com/11339137/177380621-73b237c0-83d8-440a-9f77-a4d4d5fdcff6.png)

### Atlantic Ocean
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_AtlanticOcean_temp_diff (1)](https://user-images.githubusercontent.com/11339137/177381275-271ce4b9-e0bc-4ea2-ad99-0186d395b341.png)

### Pacific Ocean
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_PacificOcean_temp_diff](https://user-images.githubusercontent.com/11339137/177381341-b5b4007a-7ff0-45a4-8156-fa0e470e8c69.png)

### Arctic
![b cesm3_cam058_mom_c B1850WscMOM ne30_L58_t061 009_Arctic_temp_diff](https://user-images.githubusercontent.com/11339137/177381399-b1866672-d166-44b6-a3b5-5ffa0252f8f8.png)

**Comment by cecilehannay** [comment]
@gustavo-marques: your plot has some similarity with what we observed when we introduced the SE dycore in CESM1.
Would you be able to do the same plot (global ocean T timeseries) for the CESM3-MOM6 with the FV dycore? I am just curious to see if it looks similar.

This is what we had with CESM1:
![Screen Shot 2022-07-05 at 11 33 07 AM](https://user-images.githubusercontent.com/9723220/177384568-e620079c-f17f-4269-9f04-5f8f0dc75714.png)

**Comment by gustavo-marques** [comment]
@cecilehannay: 

![bmom e23 f09_t061_zstar_N65 nuopc GM_tuning 002_Global_temp_diff](https://user-images.githubusercontent.com/11339137/177385093-5a8e10d3-ad8d-478c-a621-b572c55c3b1b.png)

**Comment by cecilehannay** [comment]
Thanks @gustavo-marques. The spinup is clearly different between the FV and SE dycores - once again similar to what we observed in CESM1.

Is the ocean initialization similar in SE and FV?

**Comment by gustavo-marques** [comment]
Yes, ocean initialization is identical in the SE and FV simulations. The ocean starts from rest and T&S are from the January climatology from the World Ocean Atlas 2018.

**Comment by adamrher** [comment]
Just commenting that I had previously traced that SE warm tongue ~750m to the Mediterranean outflow into the N.Atlantic. Seems to be large changes in SE there... see [here](https://webext.cgd.ucar.edu/B1850G/cesm2_2_alpha06d.poparctic_B1850G_ne30pg3_g17_1368pes_210424_aoflux-atm-hybrid-192NCPL-2macmic-125nutop-04c11b-1000mgdcs-cicealb-mammods-mg3_Nx2yrs/ocn/diag_work.1-20/MODEL_VS_OBS/TEMP1000.png) a SE-POP run I did a while back.

**Comment by gustavo-marques** [comment]
> this may be a minor point I think, but we would ideally be running with the exchange grid, as we are currently computing fluxes on the MOM grid. In `nuopc.runconfig`
> 
> ```
>      aoflux_grid = ogrid
> ```

@adamrher: do you know the namelist parameter to be running with the exchange grid?

**Comment by jedwards4b** [comment]
aoflux_grid = xgrid

**Comment by JulioTBacmeister** [comment]
So the idea here is that the SE coupled runs have two independent problems/differences from the FV
1) Warm layer at ~750m due to Mediterranean outflow
2) Surface layer/upper ocean cooling due to ???? .... but I would claim looks driven in high latitudes esp northern high latititudes?



> Just commenting that I had previously traced that SE warm tongue ~750m to the Mediterranean outflow into the N.Atlantic. Seems to be large changes in SE there... see [here](https://webext.cgd.ucar.edu/B1850G/cesm2_2_alpha06d.poparctic_B1850G_ne30pg3_g17_1368pes_210424_aoflux-atm-hybrid-192NCPL-2macmic-125nutop-04c11b-1000mgdcs-cicealb-mammods-mg3_Nx2yrs/ocn/diag_work.1-20/MODEL_VS_OBS/TEMP1000.png) a SE-POP run I did a while back.

**Comment by adamrher** [comment]
@JulioTBacmeister I'd like to know re (2), whether this is driven by local change in the column (clouds?), or changes to ocean currents. As Frank said last week, we'd expect the reduced deep convection in Labrador Sea to cool the the N.Atlantic by slowing down northward heat transport.

Did we run out FV 50 years to be sure it does not cool like SE does? If it does not, then diff'ing the surface energy budget terms should tell us whether the cooling is due to changes in the column from CAM. [Here's](https://webext.cgd.ucar.edu/BWsc1850MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/atm/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009_1_10_vs_b.e21.B1850.f09_g17.CMIP6-piControl.001_1_10/) the first ten years against each other between f09 and this run, from @justin-richling. For example, here's incident short wave at the surface, which does seem to show ~10 W/m2 reductions in large pockets in the high latitudes.

**Comment by adamrher** [comment]
I'm not familiar with the xgrid code. @mvertens? My only suspicion is that many ESMF mesh files are generated from existing SCRIP files. In the past I've ran into issues because some of our SCRIP files are [not as precise as they could be](https://sourceforge.net/p/nco/discussion/9829/thread/b933bc36e9/?limit=25#8422/8d78/e89b).

**Comment by jedwards4b** [comment]
Can you try with this version of ESMF and let me know if it works:
/glade/work/jedwards/tools/esmf/asyncio/lib/libO/Linux.intel.64.mpt.default/esmf.mk

To do this:
```
cd  /glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM_c/ccs_config
git remote add jpedev https://github.com/jedwards4b/ccs_config_cesm.git
git fetch jpedev
git checkout jedwards/cheyenne_esmf_update
```

**Comment by mvertens** [comment]
@gustavo - thanks for trying this. I'm really perplexed that this is not working. I'll try to see what is going on.

**Comment by jedwards4b** [comment]
@gustavo-marques @mvertens I found the same problem using xgrid with the newer ESMF version.

**Comment by gustavo-marques** [comment]
Thanks, @jedwards4b. I followed your instructions (updated ESMF) and it's now running:
`/glade/scratch/gmarques/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009.ogrid2/run`
It just completed 9 months.

**Comment by jedwards4b** [comment]
My case is /glade/scratch/jedwards/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009.xgrid2
I'll compare to @gustavo-marques and see if I can spot the difference.

**Comment by gustavo-marques** [comment]
@jedwards4b: my bad! I cloned the wrong case. Thanks for catching that.

**Comment by gustavo-marques** [comment]
I've set `aoflux_grid=xgrid` and resubmitted the run.

**Comment by gustavo-marques** [comment]
Ok, I am getting the same error as before.

**Comment by dabail10** [comment]
Here are the diagnostics. The sea ice is much too extensive and too thick in the Arctic. Labrador Sea freezing.

https://webext.cgd.ucar.edu/MOM/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009/ice/b.cesm3_cam058_mom_c.B1850WscMOM.ne30_L58_t061.009-obs/yrs1-63/

**Comment by gustavo-marques** [comment]
Thanks, @dabail10.
